const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS';
const FETCH_API_FAILURE = 'FETCH_API_FAILURE';
const FETCH_API_REQUEST = 'FETCH_API_REQUEST';

export { FETCH_API_FAILURE, FETCH_API_SUCCESS, FETCH_API_REQUEST };
