const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS';
const FETCH_API_FAILURE = 'FETCH_API_FAILURE';
const FETCH_API_REQUEST = 'FETCH_API_REQUEST';
const FILTER_MARKETS = 'FILTER_MARKETS';
const FILTER_CURRENCY = 'FILTER_CURRENCY';

const FETCH_MARKET_API_SUCCESS = 'FETCH_MARKET_API_SUCCESS';
const FETCH_MARKET_API_FAILURE = 'FETCH_MARKET_API_FAILURE';
const FETCH_MARKET_API_REQUEST = 'FETCH_MARKET_API_REQUEST';

export {
  FETCH_API_FAILURE,
  FETCH_API_SUCCESS,
  FETCH_API_REQUEST,
  FETCH_MARKET_API_FAILURE,
  FETCH_MARKET_API_SUCCESS,
  FETCH_MARKET_API_REQUEST,
  FILTER_MARKETS,
  FILTER_CURRENCY,
};
